### DISCUSSION TITLE
Connection to server lost, will attempt reconnection.

### DISCUSSION THREAD

**Discussion by ForestQ** [TheNickOfTime/handbrake-web#141] [General]
Hi!
The worker on the same machine in the same Docker instance doesn't want to connect. I tried both 127.0.0.1 and the real IP. What should I do?

handbrake-web-worker  | [worker] The worker process has started.
handbrake-web-worker  | [worker] [server] Connection to server lost, will attempt reconnection...

```
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 0:0
    ports:
      - 9999:9999
    volumes:
      - /home/forestq/handbrake:/data
      - /mnt/storage2:/video #ensure this path is the same across all containers

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 0:0
    environment:
      - WORKER_ID=server #give your worker a unique name
      - SERVER_URL=10.3.5.32 #set to the url or ip of your server
      - SERVER_PORT=9999 #if using a reverse proxy, this may be different than what is set above
    volumes:
      - /mnt/storage2:/video #ensure this path is the same across all containers
    depends_on:
      - handbrake-server
```
