### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by tristan-k** [TheNickOfTime/handbrake-web#123]
I'm running `Proxmox 8.2.4` with an Alpine Docker LXC. My `docker-compose.yml` looks like this:

```
services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 0:1000
    ports:
      - 9999:9999
    volumes:
      - ./data:/data
      - /root/docker/tvheadend/recordings:/video

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 0:1000
    environment:
      - WORKER_ID=alpine-docker-lxc
      - SERVER_URL=192.168.XXX.XX
      - SERVER_PORT=9999
    volumes:
      - /root/docker/tvheadend/recordings:/video
    depends_on:
      - handbrake-server
```

But the `handbrake-web-server` keeps exiting with an error in the logs:

```
> handbrake-web@0.0.0 prod
> tsx src/server.ts
[server] [presets] Presets path is '/data/presets.json'
[server] [env] The server port is 'undefined'.
[server] [env] The data path is '/data'.
[server] [env] The video path is '/video'.
[server] [config] No config file exists, copying the template config.yaml

node:fs:3002
  binding.copyFile(
          ^
Error: ENOENT: no such file or directory, copyfile '/handbrake-web/server/template/config.yaml' -> '/data/config.yaml'
    at Object.copyFileSync (node:fs:3002:11)
    at LoadConfig (/handbrake-web/server/src/scripts/config.ts:17:6)
    at Shutdown (/handbrake-web/server/src/server.ts:31:1)
    at Object.<anonymous> (/handbrake-web/server/src/server.ts:42:10)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.transformer (/handbrake-web/server/node_modules/tsx/dist/register-CCR7NebB.cjs:3:1101)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24) {

  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/handbrake-web/server/template/config.yaml',
  dest: '/data/config.yaml'
}
Node.js v22.6.0
```
