### ISSUE TITLE
Video is not converted into specified file-format

### ISSUE THREAD

**Issue by VanillaChief** [TheNickOfTime/handbrake-web#245]
### Bug Description
When attempting to convert a video file using HandBrake Web, the application fails to convert the file to the specified format. I expect the file to be saved in the chosen video format, but the output remains unchanged, as if the conversion settings were ignored. I am not sure if I set it up wrong or something is actually not working right. Please advise.

### Bug Steps
1. Import Preset, which specifies that the file should be converted to mp4
2. Watcher set up with this preset finds a .mkv files
3. After conversion, the output is still mkv
4. When using the preset with Handbrake Desktop, it works like expected

### Additional Information
<img width="1070" alt="Screenshot 2024-10-26 at 08 48 59" src="https://github.com/user-attachments/assets/65d71df6-db2a-4a62-ab6d-046df0d74597">
<img width="1069" alt="Screenshot 2024-10-26 at 08 49 06" src="https://github.com/user-attachments/assets/5c518a88-1136-481c-8f7c-1d933e2a7889">
<img width="1108" alt="Screenshot 2024-10-26 at 08 49 18" src="https://github.com/user-attachments/assets/f01a44ea-b03f-4b54-9c2c-3b6651b04d29">

### HandBrake Web Version
- v0.7.1

### Docker Compose
```yaml
services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    ports:
      - 8994:9999
    volumes:
      - ./data:/data
      - ./media:/video # ensure this path is the same across all containers
      - ./output:/output

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    environment:
      - WORKER_ID=handbrake-worker # give your worker a unique name
      - SERVER_URL=xxx.xxx.xxx.xx # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=8994 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - ./media:/video # ensure this path is the same across all containers
      - ./output:/output
    depends_on:
      - handbrake-server
```

### Host Machine
- OS: Debian 12
- CPU: i7-8700T
