### ISSUE TITLE
The worker container can run more than one handbrake cli process at once

### ISSUE THREAD

**Issue by Sleuth56** [TheNickOfTime/handbrake-web#291]
### Bug Description
I have a server instance running with a worker. The exact docker compose listed in the README.md file
I have an additional worker running on a separate computer connecting over NFS to the main server.
I have 3 workers running according to the webui. One worker shows up as N/A under worker name.
The progress bars are advancing on each of the 3 tasks.

The bug seems to crop up when restarting workers or when the server crashes and restarts.

### Bug Steps
I'm not really sure how to reproduce this. My best guess is as follows.
1. Use the docker compose to create a server and worker.
2. Use just the worker part of the docker compose to add an additional worker to the server.
3. Mess around a bit with it. Restarting workers seems to make this happen more often.
4. Notice that there is an extra worker with the name N/A.

### Additional Information
![image](https://github.com/user-attachments/assets/962c112c-894f-448b-988c-2beaabe7b66f)

### HandBrake Web Version
v0.7.3

### Docker Compose
```yaml
services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    ports:
      - 9999:9999
    volumes:
      - ./data:/data
      - /mainpool/movies:/movies # ensure this path is the same across all containers

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    cpus: 10 # Limit CPU usage to 50%
    container_name: handbrake-web-worker
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    environment:
      - WORKER_ID=handbrake-worker # give your worker a unique name
      - SERVER_URL=handbrake-server # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /mainpool/movies:/movies # ensure this path is the same across all containers
    depends_on:
      - handbrake-server
```

```yaml
services:
  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    #cpus: 6 # Limit CPU usage to 50%
    container_name: handbrake-web-worker
    user: 1000:1000
    environment:
      - WORKER_ID=desktop # MAKE SURE IT'S UNIQUE
      - SERVER_URL=10.150.1.10
      - SERVER_PORT=9999
    volumes:
      - movies:/movies

volumes:
    movies:
        driver_opts:
          type: "nfs"
          o: "addr=10.150.1.10,nolock,hard,rw,nfsvers=4.2"
          device: ":/mainpool/movies"
```

### Host Machine
- OS: Proxmox 6.8.12-1-pve
- CPU: Ryzen 3600
- GPU: N/A

### Log Information
This is from the other machine running just the single worker. This is a problem I have seen many times even when only running one worker so I don't think this is a problem related to my setup of an additional worker. Somehow the container can run more than one job at a time in one container.
```bash
[user machine]$ docker compose top
handbrake-web-worker
UID       PID    PPID   C    STIME   TTY   TIME       CMD
1000   3841   3817   0    09:21   ?     00:00:00   /usr/bin/dumb-init -- npm run prod                                                                                                                                                    
1000   3877   3841   0    09:21   ?     00:00:00   npm run prod                                                                                                                                                                          
1000   3888   3877   0    09:21   ?     00:00:00   sh -c tsx src/worker.ts                                                                                                                                                               
1000   3889   3888   0    09:21   ?     00:00:00   node /handbrake-web/worker/node_modules/.bin/tsx src/worker.ts                                                                                                                        
1000   3900   3889   0    09:21   ?     00:00:11   /usr/local/bin/node --require /handbrake-web/worker/node_modules/tsx/dist/preflight.cjs --import file:///handbrake-web/worker/node_modules/tsx/dist/loader.mjs src/worker.ts          
1000   3913   3900   0    09:21   ?     00:00:01   /handbrake-web/worker/node_modules/@esbuild/linux-x64/bin/esbuild --service=0.23.1 --ping                                                                                             
1000   3922   3900   0    09:21   ?     00:00:01   /handbrake-web/worker/node_modules/@esbuild/linux-x64/bin/esbuild --service=0.23.1 --ping                                                                                             
1000   6799   3900   99   10:13   ?     03:03:38   HandBrakeCLI --preset-import-file /tmp/preset.json --preset Jellyfin 480p -i /movies/movie1/movie1-Original.mkv -o /movies/movie1/movie1-480p.transcoding.mp4 --json  
1000   7673   3900   99   10:29   ?     01:32:51   HandBrakeCLI --preset-import-file /tmp/preset.json --preset Jellyfin 1080p -i /movies/movie2/movie2-Original.mkv -o /movies/movie2/movie2-1080p.transcoding.mp4 --json
```
The actual logs from that container go back and forth between two percentages so that data also backs up the running two instances of handbrake theory.
