### ISSUE TITLE
Server crashes when moving around items in the queue

### ISSUE THREAD

**Issue by Sleuth56** [TheNickOfTime/handbrake-web#292]
### Bug Description
When you move an item in the queue it crashes the server.

### Bug Steps
1. Standard setup with docker compose
2. Add a few items to the queue so that some are pending.
3. Try to move an item.

### HandBrake Web Version
- vX.X.X

### Docker Compose
```yaml
services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    ports:
      - 9999:9999
    volumes:
      - ./data:/data
      - /mainpool/movies:/movies # ensure this path is the same across all containers

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    cpus: 10 # Limit CPU usage to 50%
    container_name: handbrake-web-worker
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    environment:
      - WORKER_ID=handbrake-worker # give your worker a unique name
      - SERVER_URL=handbrake-server # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /mainpool/movies:/movies # ensure this path is the same across all containers
    depends_on:
      - handbrake-server
```

### Host Machine
- OS: Proxmox 6.8.12-1-pve
- CPU: Ryzen 3600
- GPU: N/A

### Log Information
```
handbrake-web-server  | 15:27:38 [server] [database] Updating job with id 'job-id-53' from order index 4 to 5
handbrake-web-server  | 15:27:38 [server] [database] Updating job with id 'job-id-53' from order index 3 to 4
handbrake-web-server  | 15:27:38 [server] [database] Updating job with id 'job-id-53' from order index 2 to 3
handbrake-web-server  | 15:27:38 [server] [database] Updating job with id 'job-id-53' from order index undefined to 2
handbrake-web-server  | 15:27:50 [server] [socket] Client is requesting job at order index undefined be reordered to index 33.
handbrake-web-server  | 15:27:50 [server] [database] Updating job with id 'job-id-53' from order index undefined to 33
handbrake-web-server  | 
handbrake-web-server  | /handbrake-web/server/src/scripts/database/database-queue.ts:326
handbrake-web-server  |                 orderUpdateStatement.run({ id: row.job_id, new_index: row.new_index });
handbrake-web-server  |                                      ^
handbrake-web-server  | 
handbrake-web-server  | SqliteError: UNIQUE constraint failed: jobs_order.order_index
handbrake-web-server  |     at <anonymous> (/handbrake-web/server/src/scripts/database/database-queue.ts:326:24)
handbrake-web-server  |     at Array.forEach (<anonymous>)
handbrake-web-server  |     at UpdateJobOrderIndexInDatabase (/handbrake-web/server/src/scripts/database/database-queue.ts:325:15)
handbrake-web-server  |     at Socket.<anonymous> (/handbrake-web/server/src/socket/client-socket.ts:120:4)
handbrake-web-server  |     at Socket.emit (node:events:513:28)
handbrake-web-server  |     at Socket.emitUntyped (/handbrake-web/server/node_modules/socket.io/dist/typed-events.js:69:22)
handbrake-web-server  |     at /handbrake-web/server/node_modules/socket.io/dist/socket.js:697:39
handbrake-web-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
handbrake-web-server  |   code: 'SQLITE_CONSTRAINT_UNIQUE'
handbrake-web-server  | }
handbrake-web-server  | 
handbrake-web-server  | Node.js v23.3.0
handbrake-web-server  | 
handbrake-web-server  | > handbrake-web@0.7.3 prod
handbrake-web-server  | > tsx src/server.ts
handbrake-web-server  | 
handbrake-web-server  | 15:28:58 [server] [config] [validation] The config data has passed validation.
handbrake-web-server  | 15:28:58 [server] [config] The config file at '/data/config.yaml' has been loaded.
handbrake-web-server  | 15:28:58 [server] [presets] Default presets have been loaded from '/handbrake-web/server/src/template/default-presets.json'.
handbrake-web-server  | (node:29) [DEP0178] DeprecationWarning: dirent.path is deprecated in favor of dirent.parentPath
handbrake-web-server  | (Use `node --trace-deprecation ...` to show where the warning was created)
handbrake-web-server  | 15:28:58 [server] [presets] 3 presets have been loaded from '/data/presets'.
handbrake-web-server  | 15:28:58 [server] [database] The database connection has been initalized!
handbrake-web-server  | 15:28:58 [server] [queue] Existing queue status 'Active' retreived from the database.
handbrake-web-server  | 15:28:58 [server] [database] Removing job with id '7' from the 'jobs_order' table.
```
