### ISSUE TITLE
Error on rename of transcoded file

### ISSUE THREAD

**Issue by bitmux** [TheNickOfTime/handbrake-web#298]
> [!important]
> Have you searched existing issues (both open and closed) for the issue you are having? If not, please consider doing so - your issue may already be fixed or in discussion!

Yes

### Bug Description
Node finishes transcode and then fails to rename the resulting file from filename.transcoding.mkv to filename.mkv.  This also causes the node to stop accepting new jobs (I assume that's intentional because an error occurred).  The specific file which is to be renamed does NOT exist in my transcodeOut directory.  I have no idea where it went in this case.  I did sanitize my input filenames and paths, there are no special characters (such as ' or ?)
I also tried explicitly mapping the output folder in Docker as well:
```
volumes:
  - /video:/video
  - /video/output:/video/output
```
### Bug Steps

Workers are mapped to an SMB share. This share does have simple user credentials.  UID/GID mapping completed on the worker nodes as well to ensure write permission. I've proven that workers and server are able to write to the share (share hosted on the same machine as web transcoder server).

Input filename:
1. S02E35 - Extras - Jello Commercial [DVD-480p].mkv copied to SMB share on server, job queued and then queue started.
2. Worker node accepts and transcodes file, evidence of transcode completion occasionally includes working output file which still contains the ".transcoding" flag as part of the file name
3. Bug occurs on the worker node and it then trips offline, unable to continue the queue.

### HandBrake Web Version
[v0.7.3](https://github.com/TheNickOfTime/handbrake-web/releases/tag/v0.7.3)

### Docker Compose
```yaml
services: 
  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    devices:
      - /dev/dri:/dev/dri
    environment:
      - WORKER_ID=node5 # give your worker a unique name
      - SERVER_URL=http://ripper.lan # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /mnt/media:/video # ensure this path is the same across all
      - /mnt/media/transcodeOut:/video/transcodeOut #didn't work
```

### Host Machine
- OS: Proxmox
- CPU: i5-9500T
- GPU: i915 (not in use for this test)

### Log Information
```

20:02:24 [sled3] [transcode] 

Encode done!

20:02:24 [sled3] [transcode] 
HandBrake has exited.

20:02:24 [sled3] [transcode] [muxing] 0.00 %
node:fs:1021
  binding.rename(
          ^

Error: ENOENT: no such file or directory, rename '/video/transcodeOut/S02E35 - Extras - Jello Commercial [DVD-480p].transcoding.mkv' -> '/video/transcodeOut/S02E35 - Extras - Jello Commercial [DVD-480p].mkv'
    at Object.renameSync (node:fs:1021:11)
    at Socket.<anonymous> (/handbrake-web/worker/src/scripts/transcode.ts:172:14)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/transcodeOut/S02E35 - Extras - Jello Commercial [DVD-480p].transcoding.mkv',
  dest: '/video/transcodeOut/S02E35 - Extras - Jello Commercial [DVD-480p].mkv'
}

Node.js v23.3.0
```

> [!tip]
> Please ensure all sections have been filled out with the requested information and the information is properly formatted. Issues with missing/poorly formatted information make giving help more difficult!
