### ISSUE TITLE
Workers seem to disconnect and reconnect

### ISSUE THREAD

**Issue by codesterribly** [TheNickOfTime/handbrake-web#320]
> [!important]
> Have you searched existing issues (both open and closed) for the issue you are having? If not, please consider doing so - your issue may already be fixed or in discussion!

### Bug Description
I have 3 workers (including the server): master, monitor and worker

It seems like I can only really ever have two of them running queue items at a time. The other just seems be stuck forever in "Scanning..." with a buggy % like 'NaN'

### Bug Steps
Added all three, including the master, and only two seem to connect properly, even though they queue up just fine.

### Additional Information
Any additional information or screenshots related to your issue.

### HandBrake Web Version
- latest, as of March 19, 2025

### Docker Compose
```yaml
services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    ports:
      - 9999:9999
    volumes:
      - /media/hg12/transcode:/data-in
      - /media/hg12/transcode:/video # ensure this path is the same across all containers

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    environment:
      - WORKER_ID=handbrake-workermaster # give your worker a unique name
      - SERVER_URL=http://192.168.1.200 # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /media/hg12/transcode:/video # ensure this path is the same across all containers
    depends_on:
      - handbrake-server

and each worker has its own, with a tweaked ID

services:
  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    environment:
      - WORKER_ID=handbrake-workermon # give your worker a unique name
      - SERVER_URL=http://192.168.1.200 # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /media/hg12/transcode:/video # ensure this path is the same across all containers


```

### Host Machine
- OS: Ubuntu 24.10
- CPU: Intel and AMD
- GPU: built-in 

### Log Information
```
Provide any relevant sections of your log here
```

> [!tip]
> Please ensure all sections have been filled out with the requested information and the information is properly formatted. Issues with missing/poorly formatted information make giving help more difficult!
