### ISSUE TITLE
Evaluate current state of hardware transcoding support

### ISSUE THREAD

**Issue by TheNickOfTime** [TheNickOfTime/handbrake-web#88]
I believe it should just work by default, but I have not tested this. Additionally documentation needs to be made for setting up a worker container with hw transcoding support.

**Comment by TheNickOfTime** [comment]
## NVENC Support
Tested on windows via WSL2 and Docker Desktop. NVENC seems to work out of the box if the proper compose config is used:
```
  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:main
    container_name: handbrake-web-worker
    user: 1000:1000 #edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root.
    environment:
      - WORKER_ID=windows-worker #give your worker a unique name
      - SERVER_URL=handbrake-server #set to the url or ip of your server, prefix with http:// or https://
      - SERVER_PORT=9999 #if using a reverse proxy, this may be different than what is set above
    volumes:
      - ./data:/data
      - ./media:/video #ensure this path is the same across all containers
    depends_on:
      - handbrake-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
```

**Comment by TheNickOfTime** [comment]
## QSV Support
Tested on an Intel NUC with a Pentium J5005 processor (with integrated graphics). It was necessary to edit the worker Dockerfile to install both the mesa and intel gpu drivers. The following compose file passes thru intel gpu devices to the container:
```yaml
  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 1000:1000
    environment:
      - WORKER_ID=handbrake-worker
      - SERVER_URL=http://handbrake-server
      - SERVER_PORT=9999
    volumes:
      - ./data/data:/data
      - ./data/media:/video
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - handbrake-server
```

Additionally there are a few other issues users may encounter when setting this up:
1. QSV would appear as available to handbrake, but fail once a job is started. It may be necessary for some users to add the video group to their compose file. You can get this number on your host machine via `getent group video` - mine was 44, but your may be different.
    ```yaml
    group_add:
      - 44
    ```
2. It seems that some iGPUs will fail to encode with QSV no matter what unless the following is added to your preset's advanced video options:
    ```
    lowpower=0
    ```
    More information about this can be found at HandBrake's documentation [here](https://handbrake.fr/docs/en/latest/technical/video-qsv.html).

All that said, I am not super confident that this setup will apply to all intel GPUs, especially the discrete ARC GPUs. If you encounter any issues, please open a new issue!
